name: Github Package

on:
  workflow_call

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}

jobs:
  bide:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Registry Login
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.BUILD_PAT}}

      - name: BACK Build and push to GH Package
        uses: docker/build-push-action@v4
        with:
          context: backend
          push: true
          tags: ${{env.REGISTRY}}/philepp790/back-ausecours:latest
      
      - name: FRONT Build and push to GH Package
        uses: docker/build-push-action@v4
        with:
          context: frontend
          push: true
          tags: ${{env.REGISTRY}}/philepp790/front-ausecours:latest