name: Github Package

on:
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}  # ✅ Ajout d'un espace après `${{`

jobs:
  bide:
    runs-on: ubuntu-latest
    steps:
      - name: Just for test1
        run: |
          ls -al
          pwd

      - name: Checkout
        uses: actions/checkout@v3

      - name: Just for test2
        run: |
          ls -al
          pwd

      - name: Registry Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}  # ✅ Ajout d'un espace après `${{`
          username: ${{ github.actor }}  # ✅ Ajout d'un espace après `${{`
          password: ${{ secrets.BUILD_PAT }}  # ✅ Ajout d'un espace après `${{`

      - name: Build and push to GH Package
        uses: docker/build-push-action@v4
        with:
          context: backend
          push: true
          tags: ${{ env.REGISTRY }}/philepp790/back-ausecours:latest  # ✅ Ajout d'un espace après `${{`
