name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: The First
        run: |
          echo Hello
          return 1

  test2:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: The Second
        run: echo Good Bye