name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Backend:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    services:
      mariadb:
        image: mariadb:latest
        env:
          MARIADB_ROOT_PASSWORD: toor
          MARIADB_DATABASE: test
          MARIADB_USER: test
          MARIADB_PASSWORD: test
        ports:
          - 3306:3306
        options: > 
          --health-cmd="healthcheck.sh --connect --innodb_initialized" 
          --health-interval=10s --health-timeout=5s --health-retries=3

    env:
      BDD_HOST: 127.0.0.1
      BDD_NAME: test
      BDD_USER: test
      BDD_PASS: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Database Connection Check
        run: |
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port 3306 -u root -ptoor -e "SHOW DATABASES"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm i

      - name: Initialize Database
        run: npm run initbdd

      - name: Populate Database
        run: |
          mysql -u root -ptoor --host 127.0.0.1 --port 3306 --database test < ./test/insert_test_user.sql
      
      - name: Run Tests and Coverage
        run: npm run test:cov

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: back-coverage-report
          path: backend/coverage
          retention-days: 3

  Frontend:
    needs: [Backend]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start Backend Build
        run: |
          cd backend
          docker compose -f docker-compose-build.yml up -d
          docker ps -a

      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'
      
      - name: Test Backend Container
        if: success()
        run: curl http://127.0.0.1:23000

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install Cypress & Dependencies
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          working-directory: frontend

      - name: Install Dependencies
        run: npm i

      - name: Start Cypress E2E Tests
        uses: cypress-io/github-action@v6
        with: 
          install: false
          working-directory: frontend
          start: npm run dev

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: frontend/cypress/screenshots
          retention-days: 1

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: frontend/cypress/videos
          retention-days: 3

      - name: Clean Backend Docker
        if: always()
        run: |
          cd backend
          docker compose -f docker-compose-build.yml down

  Biderie:
    if: github.event_name == 'push'
    uses: ./.github/workflows/ghcr.yaml
    secrets: inherit
    permissions:
      contents: read
      packages: write

  Chelouterie:
    needs: [Biderie]
    uses: ./.github/workflows/canary.yaml
    secrets: inherit
    permissions:
      id-token: write
