name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: The First
        run: |
          echo Hello

  test2:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: The Second
        run: echo "Good Bye"

  bideris:
    needs: [test2]
    uses: ./.github/workflows/ghcr.yaml
    secrets: inherit  

  Chelouterie:
    needs: [bideris]
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit

  coulou:  
    needs: [Chelouterie]
    uses: ./.github/workflows/canary.yaml
    secrets: inherit
    permissions:
      id-token: write
