name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: The First
        run: |
          echo Hello

  test2:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: The Second
        run: echo "Good Bye"

  bideris:
    needs: [test2]
    uses: ./.github/workflows/ghcr.yaml
    secrets: inherit  # ✅ Permet de transmettre tous les secrets
